microsoft/fabric-cicd

- src/fabric_cicd/_items/_datapipeline.py
This pull request includes changes to the `src/fabric_cicd/_items/_datapipeline.py` file to improve the method for finding referenced data pipelines. The most important changes include importing the `re` module, renaming a method, and updating the logic for identifying pipeline references.
Improvements to data pipeline reference identification:
* [`src/fabric_cicd/_items/_datapipeline.py`](diffhunk://#diff-f5d57c243b415de3d1c44d5e1084f6301e90adaef563daecf4439dbc217dc254R3): Imported the `re` module to use regular expressions for pattern matching.
* [`src/fabric_cicd/_items/_datapipeline.py`](diffhunk://#diff-f5d57c243b415de3d1c44d5e1084f6301e90adaef563daecf4439dbc217dc254R117-R132): Added a regular expression pattern `guid_pattern` to identify GUIDs in the JSON data.
* …
> Update Find Referenced Pipelines Function

- .github/ISSUE_TEMPLATE/1-bug.yml
- .github/ISSUE_TEMPLATE/3-documentation.yml
- .github/ISSUE_TEMPLATE/4-question.yml
- .github/ISSUE_TEMPLATE/5-tech-debt.yml
This pull request includes several changes to the GitHub issue templates to improve their clarity and usability. The most important changes involve removing default titles, changing input types, and adding a new template for technical debt.
Improvements to existing templates:
* [`.github/ISSUE_TEMPLATE/1-bug.yml`](diffhunk://#diff-6776d62e4a2433668f6f50806c424a3f35f7c39b885e14ce2dc35ca8510b861aL3-R10): Removed the default title and changed the input type for steps to reproduce from `input` to `textarea`.
* [`.github/ISSUE_TEMPLATE/2-feature.yml`](diffhunk://#diff-1ec81c5c8c2cd65f57c32fb1f61ed32d7c1afb286ef327bed07d3b5acd0d4a8bL3-R3): Removed the default title and the placeholder text in the problem description section. [[1]](diffhunk://#diff-1ec81c5c8c2cd65f57c32fb1f61ed32d7c1afb286ef327be …
> Onboard Tech Debt Form & Fixes #26

- README.md
- docs/about.md
- docs/index.md
- mkdocs.yml
This pull request includes several documentation updates and improvements to the `fabric-cicd` project. The most important changes include updating the section overview in the `README.md`, renaming the `help.md` file to `about.md`, adding installation instructions for the private preview, and updating the navigation in the `mkdocs.yml` file.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L20-R25): Updated the section overview links to reflect the new structure and consolidated support and security policies under the "About" section.
* `docs/help.md` renamed to `docs/about.md`: Renamed the file to better reflect its content, which includes support and security information.
* …
> Update Readme Fixes #43

- docs/index.md
This pull request includes a change to the `docs/index.md` file to simplify the installation instructions for `fabric-cicd`.
Documentation update:
* Removed the instructions for installing `fabric-cicd` during the private preview phase, leaving only the standard installation command.
> Remove Private Preview References

- src/fabric_cicd/_common/_fabric_endpoint.py
This pull request includes several changes to the `invoke` method in the `src/fabric_cicd/_common/_fabric_endpoint.py` file, focusing on improving error handling and retry logic for API requests. The most important changes include the addition of a new `_handle_retry` method, enhanced error messaging, and improved handling of API throttling and long-running operations.
Improvements to error handling and retry logic:
* Added a new `_handle_retry` method to handle retry logic with exponential backoff based on the response headers. This method is called when the `Retry-After` header is present in the response.
* Enhanced error messaging for failed operations and deployment attempts, improving readability and clarity. [[1]](diffhunk://#diff-df48b77e163b4a13c97f80408ad6640fca48ffdc60c19e085b4c7 …
> Introduce retry with backoff

- src/fabric_cicd/_common/_fabric_endpoint.py
Solves an issue with `int.is_integer()` not being available in Python versions < 3.12.
closes #63
> Fixed integer check

- sample/auth_spn_secret.py
- src/fabric_cicd/fabric_workspace.py
This pull request includes a minor change to the `src/fabric_cicd/fabric_workspace.py` file. The change updates the description of the `repository_directory` parameter in the `__init__` method to clarify that it refers to the local directory path of the repository where items are to be deployed from.
* [`src/fabric_cicd/fabric_workspace.py`](diffhunk://#diff-3bd0f70ed06c7fc7a0f77378aecc6fb108eeb5263161db3b22270f3de4df99c0L45-R45): Updated the description of the `repository_directory` parameter in the `__init__` method to clarify its purpose.
> Fixes #64, Fixes #65 - Documentation Updates

- README.md
The existing How To link gave a 404 - fixed it to linke to the three sub-pages. If that's not how you want the links to be, well at least now you know the link is broken :)
> Fixes #92 - Broken README Link

- .vscode/settings.json
- pyproject.toml
- requirements-dev.txt
- ruff.toml
- src/fabric_cicd/_common/_fabric_endpoint.py
- tests/test_fabric_endpoint.py
- uv.lock
This pull request introduces several changes to improve the testing setup, dependency management, and robustness of the `FabricEndpoint` class. The most important changes include enabling and configuring `pytest`, adding new dependencies, and refactoring the `FabricEndpoint` class to handle token refresh and logging more effectively.
Testing and dependencies:
* [`.vscode/settings.json`](diffhunk://#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357L56-R61): Enabled `pytest` for testing and configured it to look for tests in the `tests` directory.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R28-R31): Added `pytest`, `pytest-mock`, `ruff`, and `coverage` to the development dependencies and configured `pytest` …
> Test Fabric Endpoint

- src/fabric_cicd/_items/_environment.py
This pull request includes a change to the `_remove_libraries` function in the `src/fabric_cicd/_items/_environment.py` file to improve the handling of the `environmentYml` key in the response body.
Improvements to `_remove_libraries` function:
* [`src/fabric_cicd/_items/_environment.py`](diffhunk://#diff-d21d8d1ab1b91c6581949c76a61d12d3f838509ef127b4ae5144feb5bc23bd8aL179-R183): Modified the condition to check if `response_environment["body"]["environmentYml"]` is not None or an empty string before calling `_remove_library` for `environment.yml`.
> Fixes #103 - Environment Failure without Public Library

- .prettierignore
- .prettierrc
- .vscode/settings.json
- src/fabric_cicd/_items/_report.py
- src/fabric_cicd/_items/_semanticmodel.py
- src/fabric_cicd/fabric_workspace.py
This pull request includes updates to the formatting configuration and improvements to the `fabric_cicd` module. The most important changes include adding Prettier configuration files, updating VSCode settings for formatting, and refactoring the `_publish_item` method to use a regex for excluding paths.
* [`.prettierignore`](diffhunk://#diff-b640b344ee7f3f03d2a443795a5d0708ef50e2e6e34214109ab2aad13ad6ba98R1): Added `sample/workspace/` to ignore list.
* [`.prettierrc`](diffhunk://#diff-663ade211b3a1552162de21c4031fcd16be99407aae5ceecbb491a2efc43d5d2R1-R7): Added Prettier configuration with specific formatting rules.
* [`.vscode/settings.json`](diffhunk://#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357L3-R5): Updated VSCode settings to use Prettier as the default …
> Resolves #28 - Leverage UpdateDefinition Flag

- docs/how_to/parameterization.md
- sample/workspace/parameter.yml
This pull request includes updates to the `docs/how_to/parameterization.md` file to provide a more comprehensive example of the `find_replace` functionality. The changes add a detailed use case and example configurations for replacing connection strings in different environments.
Documentation improvements:
* [`docs/how_to/parameterization.md`](diffhunk://#diff-9cdd02ee5f5219c5426160beb19ff83c624221fd6db2ac6f8bf923d6ebb6f0ffL9-R9): Added an example use case to illustrate the `find_replace` functionality, including a sample `Parameters.yml` configuration and a `notebook-content.py` file to demonstrate how lakehouse and workspace IDs are replaced during deployment. [[1]](diffhunk://#diff-9cdd02ee5f5219c5426160beb19ff83c624221fd6db2ac6f8bf923d6ebb6f0ffL9-R9) …
> Resolves #110 Need more examples for Find_replace docs page

- src/fabric_cicd/_common/_check_utils.py
This pull request introduces a new utility function to parse the changelog and integrates it into the version check process. The most important changes include the addition of the `parse_changelog` function, updates to the `check_version` function to display changelog entries, and the import of the `re` module.
Enhancements to changelog handling:
* [`src/fabric_cicd/_common/_check_utils.py`](diffhunk://#diff-ed3713e24dab32c1a8de7fc474ab489877af35d51d709421fe8a708d7dc6221fR21-R89): Added the `parse_changelog` function to parse the changelog file and return a dictionary of versions with their changes.
* [`src/fabric_cicd/_common/_check_utils.py`](diffhunk://#diff-ed3713e24dab32c1a8de7fc474ab489877af35d51d709421fe8a708d7dc6221fR21-R89): Updated the `check_version` function to use …
> Resolves #127 - Share changelog with version check

- docs/how_to/parameterization.md
- src/fabric_cicd/_common/_validate_input.py
- src/fabric_cicd/fabric_workspace.py
This pull request includes several changes to improve the handling of file paths and directory validation in the `fabric_cicd` module. The most important changes include modifying the `validate_repository_directory` function to return a `Path` object, updating the `__init__` method to reflect this change, and refactoring various methods to use `Path` objects more consistently.
* [`src/fabric_cicd/_common/_validate_input.py`](diffhunk://#diff-b8a669357b50d9b4d808c610b3e17e12321db4f234259b95ba4350adcca0ecd8L77-R97): Modified `validate_repository_directory` to return a `Path` object instead of a string, and added logic to resolve relative paths to absolute paths.
* [`src/fabric_cicd/fabric_workspace.py`](diffhunk://#diff-3bd0f70ed06c7fc7a0f77378aecc6fb108eeb5263161db3b22270f3de4df99c0L105-R10 …
> Fixes #136, #132 - Support Relative Directories

- src/fabric_cicd/_items/_report.py
This resolves an issue where an null byPath object appears in the file, possibly due to a Report and a Semantic Model being separated earlier.
> Fixes #143 - error loading report definition file

- docs/how_to/item_types.md
- sample/workspace/MirroredDatabase_1.MirroredDatabase/.platform
- sample/workspace/MirroredDatabase_1.MirroredDatabase/mirroring.json
- src/fabric_cicd/_items/__init__.py
- src/fabric_cicd/_items/_mirroreddatabase.py
- src/fabric_cicd/fabric_workspace.py
- src/fabric_cicd/publish.py
This pull request introduces support for Mirrored Database items in the Fabric CI/CD pipeline. The changes include updates to documentation, configuration files, and the addition of new functions to handle the publishing and unpublishing of Mirrored Database items.
Key changes include:
* Added a new section for Mirrored Database in `docs/how_to/item_types.md`, detailing parameterization, initial deployment requirements, and unpublish warnings.
* Added a new configuration file `sample/workspace/MirroredDatabase_1.MirroredDatabase/.platform` to define the metadata and configuration for Mirrored Database items.
* Added a new configuration file `sample/workspace/MirroredDatabase_1.MirroredDatabase/mirroring.json` to specify the properties of the source and target for the Mirrored Database.
* …
> Resolves #145 - Support for Mirrored Database

- src/fabric_cicd/_common/_fabric_endpoint.py
- tests/test__fabric_endpoint.py
This pull request includes changes to the retry logic in the `_handle_response` function and updates the corresponding test to reflect these changes. The most important changes are:
Retry logic adjustments:
* [`src/fabric_cicd/_common/_fabric_endpoint.py`](diffhunk://#diff-df48b77e163b4a13c97f80408ad6640fca48ffdc60c19e085b4c73589933178cL248-R250): Increased the `base_delay` from 2.5 seconds to 30 seconds and added a new parameter `response_retry_after` set to 300 seconds in the `handle_retry` function call.
Test updates:
* [`tests/test__fabric_endpoint.py`](diffhunk://#diff-d5975d64f0adde0e560b6984da9e6c82903b4d6c09da96d60e3051c37465497aL360-R360): Updated the expected retry message to reflect the new delay, changing the wait time from 5 seconds to 60 seconds.
> Resolves #135 - Increase reserved name wait time.

- docs/how_to/item_types.md
This pull request includes an update to the documentation for the `Mirrored Database` section. The change clarifies the behavior of the `find_replace` section in the `parameter.yml` file.
Documentation update:
* [`docs/how_to/item_types.md`](diffhunk://#diff-2b5373cf38b50a290bee3f403778f7dff7cdc942ddbb39026b291da113dc6025L29-R29): Clarified that connections will always point to the original source database unless parameterized in the `find_replace` section of the `parameter.yml` file.
> Update Mirrored Database parametization

- src/fabric_cicd/fabric_workspace.py
This pull request includes a minor but important change to the `_replace_activity_workspace_ids` method in the `fabric_workspace.py` file. The change ensures that the type value is a string before checking if it is found in the activities mapping.
* [`src/fabric_cicd/fabric_workspace.py`](diffhunk://#diff-3bd0f70ed06c7fc7a0f77378aecc6fb108eeb5263161db3b22270f3de4df99c0L287-R288): Added a type check to ensure the `activity_value` is a string before checking if it is in the `activities_mapping`.
> Resolves #164 Workspace ID replacement in data pipelines bug

- src/fabric_cicd/fabric_workspace.py
This pull request includes a change to the `FabricWorkspace` class in the `src/fabric_cicd/fabric_workspace.py` file to simplify the code by reusing an existing tuple.
Codebase simplification:
* [`src/fabric_cicd/fabric_workspace.py`](diffhunk://#diff-3bd0f70ed06c7fc7a0f77378aecc6fb108eeb5263161db3b22270f3de4df99c0L37-R37): Modified the `ACCEPTED_ITEM_TYPES_NON_UPN` tuple to reuse the `ACCEPTED_ITEM_TYPES_UPN` tuple, removing redundancy in the code.
> Resolves #133 DataPipeline SPN Support

- sample/import_args_from_ado_pipelines.py
Added import_args_from_ado_pipelines to show how to import arguments from a Python script task in Azure Pipelines through to the Python deployment script. In order to operationalize fabric-cicd by working with a script that can be used for multiple deployments in Azure DevOps.
> Added import_args_from_ado_pipelines Sample

- devtools/debug_local.py
- docs/config/pre-build/update_item_types.py
- src/fabric_cicd/__init__.py
- src/fabric_cicd/_common/_fabric_endpoint.py
- src/fabric_cicd/_common/_validate_input.py
- src/fabric_cicd/_items/_datapipeline.py
- src/fabric_cicd/constants.py
- src/fabric_cicd/fabric_workspace.py
- src/fabric_cicd/publish.py
This pull request includes several changes to the `fabric_cicd` package, primarily focusing on refactoring the use of constants and improving code maintainability. The most important changes include moving constants to a dedicated file, updating the usage of these constants throughout the codebase, and deprecating the `base_api_url` parameter in the `FabricWorkspace` class.
Refactoring and constants management:
* [`src/fabric_cicd/constants.py`](diffhunk://#diff-91c2d32be351f155f090c4bd57ebe3c10e646edbc1b663e2a72b697f956a949cR3-R28): Introduced a new file to store constants such as `ACCEPTED_ITEM_TYPES_UPN`, `FEATURE_FLAG`, and `VALID_GUID_REGEX`.
Code updates to use the new constants:
* [`docs/config/pre-build/update_item_types.py`](diffhunk://#diff-dfc7e72547f63f32daeff960bb1258340b2453b …
> Resolves #146 Move MaxRetry to Constants

- src/fabric_cicd/_parameter/_parameter.py
- src/fabric_cicd/_parameter/_utils.py
This pull request includes several changes to improve logging and simplify the parameter validation code in the `fabric_cicd` module. The primary changes involve adjusting the logging levels and removing unnecessary parameters from functions.
* Changed logging level from `info` to `debug` for validation success messages in `_validate_parameter_file`, `_validate_load_parameters_to_dict`, and `_validate_parameter` methods in `src/fabric_cicd/_parameter/_parameter.py`. [[1]](diffhunk://#diff-663a11b92ff45fa9b30ab4086a71af3d0f87fce5a8da7967ff9a1197cc24d501L94-R94) [[2]](diffhunk://#diff-663a11b92ff45fa9b30ab4086a71af3d0f87fce5a8da7967ff9a1197cc24d501L118-R118) [[3]](diffhunk://#diff-663a11b92ff45fa9b30ab4086a71af3d0f87fce5a8da7967ff9a1197cc24d501L169-R176)
* Removed the `validation` parameter …
> Resolves #113 Parameterization Refactor fix logging

- src/fabric_cicd/_common/_check_utils.py
- src/fabric_cicd/fabric_workspace.py
- src/fabric_cicd/publish.py
This pull request introduces several changes to enhance the functionality of the Fabric CICD project, particularly focusing on regex validation and item publishing control. The most important changes include the addition of a regex validation function, integration of this function into item publishing workflows, and updates to method signatures to support regex-based exclusions.
* [`src/fabric_cicd/_common/_check_utils.py`](diffhunk://#diff-ed3713e24dab32c1a8de7fc474ab489877af35d51d709421fe8a708d7dc6221fR112-R126): Added a new function `check_regex` to validate regex patterns and return the compiled pattern.
* [`src/fabric_cicd/fabric_workspace.py`](diffhunk://#diff-3bd0f70ed06c7fc7a0f77378aecc6fb108eeb5263161db3b22270f3de4df99c0R18): Imported the `check_regex` function and integrated it …
> Resolves #121 Publish Regex Exclusion

- src/fabric_cicd/_common/_check_utils.py
This pull request includes a small change to the `src/fabric_cicd/_common/_check_utils.py` file. The change adds a future import statement to support forward compatibility with type annotations. 
* [`src/fabric_cicd/_common/_check_utils.py`](diffhunk://#diff-ed3713e24dab32c1a8de7fc474ab489877af35d51d709421fe8a708d7dc6221fR6-R7): Added `from __future__ import annotations` to support forward compatibility with type annotations.
> Fixes #156 - Expand type hints support

- src/fabric_cicd/fabric_workspace.py
This pull request includes an enhancement to the `src/fabric_cicd/fabric_workspace.py` file to improve the efficiency of replacing workspace IDs in a given file. The most important change is the modification of the `_replace_workspace_ids` method to use `re.sub` for more efficient and concise replacement of default workspace IDs.
Codebase simplification:
* [`src/fabric_cicd/fabric_workspace.py`](diffhunk://#diff-3bd0f70ed06c7fc7a0f77378aecc6fb108eeb5263161db3b22270f3de4df99c0L302-R311): Modified the `_replace_workspace_ids` method to use `re.sub` for replacing all instances of the default feature branch workspace ID with the target workspace ID. This change simplifies the code and ensures all matches are replaced in one operation.
> Fixes #186 Workspace Id not updated in data pipelines

- src/fabric_cicd/_common/_item.py
- src/fabric_cicd/fabric_workspace.py
- src/fabric_cicd/publish.py
- tests/test_fabric_workspace.py
This pull request includes significant updates to the `fabric_cicd` module to enhance folder management and item publishing processes. The changes introduce new methods for handling folders and update existing methods to incorporate folder-related logic.
* [`src/fabric_cicd/fabric_workspace.py`](diffhunk://#diff-3bd0f70ed06c7fc7a0f77378aecc6fb108eeb5263161db3b22270f3de4df99c0R477-R636): Added methods `_refresh_deployed_folders`, `_refresh_repository_folders`, `_publish_folders`, and `_unpublish_folders` to manage folder structures and synchronization between the repository and deployed environments.
* [`src/fabric_cicd/publish.py`](diffhunk://#diff-a8555a82747092e8d1f2ee36f31c947b4e5a264ed6c6d8de48d8daf850372704R42-R48): Updated `publish_all_items` and `unpublish_all_orphan_items` …
> Onboard Workspace Folders

- .github/workflows/gh-pages.yml
This pull request includes a change to the `.github/workflows/gh-pages.yml` file to improve the method of extracting the `VERSION` variable.
* [`.github/workflows/gh-pages.yml`](diffhunk://#diff-c04119feaeffc2c216f069aec66797f2f839a2074287060698e3a2440dec8d45L38-R38): Changed the method of extracting the `VERSION` variable to use `grep` instead of a Python command.
> Fix Doc Publish

- devtools/debug_local.py
- docs/how_to/optional_feature.md
- src/fabric_cicd/fabric_workspace.py
- src/fabric_cicd/publish.py
This pull request introduces a new feature flag `disable_workspace_folder_publish` and updates the codebase to support this feature. The changes span across several files to ensure that the new flag is properly integrated and functional.
* [`docs/how_to/optional_feature.md`](diffhunk://#diff-c6d5a0fcefe940477d9234afcbed07e3a42c359ef09ebf0093905ea3c9c7f8f1L10-R17): Added `disable_workspace_folder_publish` to the list of feature flags.
* `src/fabric_cicd/fabric_workspace.py`: 
- Initialized new dictionaries (`repository_folders`, `repository_items`, `deployed_folders`, `deployed_items`) in the `__init__` method.
- Updated `_refresh_repository_items` method to check for the `disable_workspace_folder_publish` flag and adjust the item folder ID accordingly.
- Modified `_publish_item` method to …
> Resolves #221 & #222 - Fix Subfolders in Root

- src/fabric_cicd/fabric_workspace.py
This pull request includes changes to the `src/fabric_cicd/fabric_workspace.py` file to improve the handling of folder IDs and add debug logging for item movements. The most important changes include updating the default value for `item_folder_id` and adding a debug log statement when items are moved.
Improvements to folder ID handling:
* [`src/fabric_cicd/fabric_workspace.py`](diffhunk://#diff-3bd0f70ed06c7fc7a0f77378aecc6fb108eeb5263161db3b22270f3de4df99c0L220-R220): Changed the default value for `item_folder_id` from `None` to an empty string in the `_refresh_deployed_items` method.
Enhancements to logging:
* [`src/fabric_cicd/fabric_workspace.py`](diffhunk://#diff-3bd0f70ed06c7fc7a0f77378aecc6fb108eeb5263161db3b22270f3de4df99c0R461-R463): Added a debug log statement in the …
> Fixes #236 - Folder Move Occurring Every Publish

- src/fabric_cicd/_items/__init__.py
- src/fabric_cicd/_items/_environment.py
- src/fabric_cicd/publish.py
This pull request includes changes to enhance the environment publishing process within the `fabric_cicd` module. The most important changes include the addition of a new function to check the environment publish state, modifications to the `publish_environments` function, and updates to the environment metadata publishing process.
* [`src/fabric_cicd/_items/__init__.py`](diffhunk://#diff-94d858110d4e75a68135b9975f58e289c7db48793b5bf7bc56c08efad59f3e34L8-R8): Added `check_environment_publish_state` import and included it in the `__all__` list to make it publicly accessible. [[1]](diffhunk://#diff-94d858110d4e75a68135b9975f58e289c7db48793b5bf7bc56c08efad59f3e34L8-R8) [[2]](diffhunk://#diff-94d858110d4e75a68135b9975f58e289c7db48793b5bf7bc56c08efad59f3e34R17)
* …
> Resolves #237 - Reduce Environment Publish Time

- docs/example/authentication.md
This pull request removes outdated and unconfirmed examples from the `authentication.md` documentation file to streamline and clarify the content. The most significant change involves the removal of release pipeline script examples for Azure DevOps and GitHub.
* [`docs/example/authentication.md`](diffhunk://#diff-209795f61181441c3bebe319157e9b2dec863d464945eb609858eec490c73a9eL94-L134): Removed the "Release Pipeline Script" section, which included an Azure DevOps YAML example and a placeholder for a GitHub example. This change simplifies the documentation by eliminating unconfirmed and redundant examples.
> Fix Authentication Sample

- src/fabric_cicd/_common/_validate_input.py
- src/fabric_cicd/_items/_report.py
- src/fabric_cicd/constants.py
- src/fabric_cicd/fabric_workspace.py
This pull request introduces support for specifying a workspace by name in addition to the existing support for specifying a workspace by ID, along with other minor improvements. The key changes include updates to the `FabricWorkspace` class to handle the new `workspace_name` parameter, validation logic for workspace names, and a new method to resolve workspace IDs from names.
* Added an optional `workspace_name` parameter to the `FabricWorkspace` class, allowing users to specify a workspace by name. If both `workspace_id` and `workspace_name` are provided, `workspace_id` takes precedence. (`src/fabric_cicd/fabric_workspace.py`, [src/fabric_cicd/fabric_workspace.pyL31-R44](diffhunk://#diff-3bd0f70ed06c7fc7a0f77378aecc6fb108eeb5263161db3b22270f3de4df99c0L31-R44))
* Introduced a …
> Implements #200 - Add Workspace Name in FabricWorkspaceObject

- docs/config/pre-build/section_toc.py
This pull request introduces enhancements to the `on_page_markdown` function in `docs/config/pre-build/section_toc.py` to improve the generation of section-specific table of contents (TOC). The most notable changes include adding support for ordering markdown files based on the `nav` structure in `mkdocs.yml` and refactoring the logic to align with this new feature.
* **Support for `mkdocs.yml`-based ordering**: Added a new `get_section_order` function to recursively extract the order of markdown files from the `nav` structure in `mkdocs.yml`. This ensures that the TOC reflects the intended navigation hierarchy. (`[docs/config/pre-build/section_toc.pyR4-L22](diffhunk://#diff-63b7692ff1d1a38808672bbc1dec28f9b3ae609424e264f2fc32195e766522deR4-L22)`)
* **Integration with …
> Fix Out of Order Table of Contents

- .github/policies/sdl.yml
Add reviewer policy via yml as a workaround for current bug with SDL scan where org policies are not reflected.
> Add SDL Reviewer Policy

- src/fabric_cicd/publish.py
This pull request adds an example to the docstring of the `publish_all_items` function in `src/fabric_cicd/publish.py` to demonstrate how to use the function with a regex for excluding item names.
Documentation improvement:
* Added a new example to the `publish_all_items` function docstring, showing how to use the `item_name_exclude_r` parameter with a regex pattern (e.g., `.*_do_not_publish`) to exclude specific items during publishing. (`[src/fabric_cicd/publish.pyR41-R50](diffhunk://#diff-a8555a82747092e8d1f2ee36f31c947b4e5a264ed6c6d8de48d8daf850372704R41-R50)`)
> Add Publish Regex Example

- docs/how_to/parameterization.md
- sample/workspace/parameter.yml
- src/fabric_cicd/_items/_environment.py
- src/fabric_cicd/_parameter/_parameter.py
- src/fabric_cicd/_parameter/_utils.py
- src/fabric_cicd/constants.py
- src/fabric_cicd/fabric_workspace.py
- tests/test_fabric_workspace.py
This pull request removes support for the legacy structure of the `parameter.yml` file and updates the codebase to exclusively use the new structure. Key changes include removing legacy structure handling, simplifying parameter validation, and updating tests to align with the new format.
* Removed all references to the legacy `parameter.yml` structure, including conditional checks for "old" structure types in `_update_compute_settings` and `_replace_parameters` methods in `src/fabric_cicd/_items/_environment.py` and `src/fabric_cicd/fabric_workspace.py`. [[1]](diffhunk://#diff-d21d8d1ab1b91c6581949c76a61d12d3f838509ef127b4ae5144feb5bc23bd8aL147-L150) [[2]](diffhunk://#diff-d21d8d1ab1b91c6581949c76a61d12d3f838509ef127b4ae5144feb5bc23bd8aL160-L166) …
> Resolves #283 Deprecate old parameter file structure

- src/fabric_cicd/_parameter/_utils.py
- src/fabric_cicd/fabric_workspace.py
This pull request includes updates to ensure compliance with CodeQL recommendations by adding comments explaining the use of a default authentication mechanism when no token is provided. The changes affect two methods in the `fabric_cicd` package.
* [`src/fabric_cicd/_parameter/_utils.py`](diffhunk://#diff-08e7f8767bb7d280f82e88a77521554115ad781c1dceb4ff0a7b450d38a684abL79-R79): Added a comment in the `validate_parameter_file` method to clarify the use of `DefaultAzureCredential` as the default authentication mechanism when no token is provided. This ensures the public library adheres to best practices for authentication.
* [`src/fabric_cicd/fabric_workspace.py`](diffhunk://#diff-3bd0f70ed06c7fc7a0f77378aecc6fb108eeb5263161db3b22270f3de4df99c0L106-R106): Added a similar comment in the …
> Resolve CodeQL Violations

- src/fabric_cicd/_common/_item.py
- src/fabric_cicd/_items/_environment.py
- src/fabric_cicd/_items/_lakehouse.py
- src/fabric_cicd/_items/_variablelibrary.py
- src/fabric_cicd/fabric_workspace.py
This pull request introduces a new `publish_status` attribute to the `Item` class and incorporates logic to utilize this attribute for conditional processing of lakehouse items. The changes improve the handling of item publication status and streamline the workflows for processing shortcuts and checking SQL endpoint statuses.
* **`Item` class update**: Added a `publish_status` attribute with a default value of `"published"` to track the publication status of items. (`src/fabric_cicd/_common/_item.py`, [src/fabric_cicd/_common/_item.pyR27](diffhunk://#diff-17da534a20198c5129cf833667e9b49cbee24482df11bfff019a2e6134bd8fc8R27))
* **Conditional logic for SQL endpoint checks**: Updated the `check_sqlendpoint_provision_status` function to skip SQL endpoint status checks for items that are not …
> Resolves #277 - Operations not being skipped w/ regex_exclude on publish

- src/fabric_cicd/_items/_environment.py
This pull request refactors the logging and filtering logic in the `check_environment_publish_state` function to improve readability and handle cases where the `publish_item_name_exclude_regex` might be `None`.
* [`src/fabric_cicd/_items/_environment.py`](diffhunk://#diff-d21d8d1ab1b91c6581949c76a61d12d3f838509ef127b4ae5144feb5bc23bd8aL97-R104): Refactored the filtering logic for environments into a new `filtered_environments` variable, improving readability and ensuring the code handles cases where `publish_item_name_exclude_regex` is `None`. Updated the logging statement to use the new variable.
> Fixes #295 When publish environments in v. 0.1.17 (publish_item_name_exclude_regex is None)

- docs/how_to/item_types.md
- sample/workspace/Default.Warehouse/.platform
- sample/workspace/DefaultCaseInsensitive.Warehouse/.platform
- src/fabric_cicd/_items/__init__.py
- src/fabric_cicd/_items/_warehouse.py
- src/fabric_cicd/constants.py
- src/fabric_cicd/publish.py
This pull request introduces support to deploy empty Warehouse items allowing for the temporary unblock of issue #204. This will allow Warehouse users the ability to deploy items via `fabric-cicd` and bring their own tools for any project DDL code that must be deployed.
- Introduced a new publish_warehouses function in src/fabric_cicd/_items/_warehouse.py to handle the publishing of empty Warehouse items. These changes will dynamically support additional collations as they become supported in the future.
- Updated src/fabric_cicd/_items/__init__.py to include publish_warehouses in the module exports and imports.
- Added Warehouse to the list of accepted item types in src/fabric_cicd/constants.py.
- Modified the publish_all_items function in src/fabric_cicd/publish.py to include logic for …
> Onboard Warehouse: Empty Item and Collation Support

- src/fabric_cicd/fabric_workspace.py
- src/fabric_cicd/publish.py
This pull request includes updates to improve the handling of folder and item unpublishing in the `fabric_cicd` module. The most important changes involve optimizing the logic for determining orphaned folders and ensuring that folder metadata is refreshed during the unpublishing process.
* [`src/fabric_cicd/fabric_workspace.py`](diffhunk://#diff-3bd0f70ed06c7fc7a0f77378aecc6fb108eeb5263161db3b22270f3de4df99c0L639-R659): Refactored the `_unpublish_folders` method to improve clarity and efficiency. The logic now uses a set to track folders containing items and their parent folders, ensuring that only orphaned folders are unregistered.
* [`src/fabric_cicd/publish.py`](diffhunk://#diff-a8555a82747092e8d1f2ee36f31c947b4e5a264ed6c6d8de48d8daf850372704R226): Added a call to …
> Resolves #273 Bug when determining orphan workspace folders to unpublish

- docs/how_to/item_types.md
- sample/workspace/Sample.GraphQLApi/.platform
- sample/workspace/Sample.GraphQLApi/graphql-definition.json
- src/fabric_cicd/_items/__init__.py
- src/fabric_cicd/_items/_graphqlapi.py
- src/fabric_cicd/changelog.md
- src/fabric_cicd/constants.py
- src/fabric_cicd/publish.py
This pull request introduces support for a new `GraphQLApi` item type in the project. The changes include updates to documentation, configuration files, and the codebase to enable publishing and managing `GraphQLApi` items.
* Added a new section in `docs/how_to/item_types.md` explaining how to parameterize and deploy `GraphQLApi` items, including guidelines for using saved credentials and handling API query updates. [[1]](diffhunk://#diff-2b5373cf38b50a290bee3f403778f7dff7cdc942ddbb39026b291da113dc6025R10-R18) [[2]](diffhunk://#diff-2b5373cf38b50a290bee3f403778f7dff7cdc942ddbb39026b291da113dc6025L32-R41)
* Added a `.platform` file in `sample/workspace/Sample.GraphQLApi` to define metadata and configuration for the `GraphQLApi` item type.
* Added a `graphql-definition.json` file in …
> Resolves #287 Support for GraphQL API Item

- .github/ISSUE_TEMPLATE/6-copilot.yml
This pull request introduces a new issue template specifically for tasks assigned to the GitHub Copilot Agent. The template is designed to streamline task creation and provide focused context for Copilot-related issues.
New GitHub Copilot issue template:
* [`.github/ISSUE_TEMPLATE/6-copilot.yml`](diffhunk://#diff-425cd01e8cadf1e038cc8a3f5a4b6844969748a8c0654571a23058c2849e2c62R1-R37): Added a new issue template named "GitHub Copilot Assignment" with fields for problem description, solution description, and success criteria. This template is tailored for tasks requiring GitHub Copilot assistance, with optional fields to allow quick assignment.## Description
> Resolves #309 Copilot Issue Template

- docs/how_to/parameterization.md
- sample/workspace/Example Notebook.Notebook/notebook-content.py
- sample/workspace/parameter.yml
- src/fabric_cicd/constants.py
- src/fabric_cicd/fabric_workspace.py
- tests/test_parameter_utils.py
This PR extends the workspace items refresh functionality to support Eventhouse item type attribute `queryserviceuri` alongside the existing Lakehouse and Warehouse support of `sqlendpoint`.
The dynamic replacement for `queryserviceuri` is accessible with similar attribute form of:
`$items.Eventhouse.Sample_EH.queryserviceuri`
- Resolves #414
> Resolves #414 - Dynamic Replacement Support for Eventhouse query URI

- src/fabric_cicd/constants.py
- src/fabric_cicd/publish.py
This pull request introduces a new validation mechanism for publishing items in Fabric CI/CD workflows, ensuring that a workspace has assigned capacity unless the item type is exempt. It also includes updates to constants and imports to support this functionality.
* [`src/fabric_cicd/constants.py`](diffhunk://#diff-91c2d32be351f155f090c4bd57ebe3c10e646edbc1b663e2a72b697f956a949cR41-R43): Added `NO_ASSIGNED_CAPACITY_REQUIRED` constant, listing item types (`SemanticModel`, `Report`) that do not require assigned capacity.
* [`src/fabric_cicd/publish.py`](diffhunk://#diff-a8555a82747092e8d1f2ee36f31c947b4e5a264ed6c6d8de48d8daf850372704R55-R67): Implemented a check in `publish_all_items` to validate if the workspace has assigned capacity. If not, and the item type is not exempt, an error is …
> Resolves #402 Publishing Warehouse Returns "The feature is not available"

- README.md
This pull request includes a small update to the `README.md` file. The change updates the badge for test workflows to point to the correct file, `test.yml`, instead of the previous `unit-test.yml`.
> Resolves #441 - Tests badge

- .github/workflows/validate.yml
This pull request updates the permissions in the GitHub Actions workflow configuration file to include write access to statuses, likely to enable the workflow to update commit statuses.
* [`.github/workflows/validate.yml`](diffhunk://#diff-a5c0f08bc43f53a0451cad4a4a2e435ce55ad34183350dfae5e4b2c7dca6360bR13): Added `statuses: write` under the `permissions` section to allow the workflow to write commit statuses.## Description
Briefly describe what this PR does and why.
> Resolves #302 - Adds Permissions

- docs/config/overrides/main.html
This pull request updates the announcement banner in the documentation to clarify the status of the library.
* Documentation banner update: Changed the message in `docs/config/overrides/main.html` to indicate the library is open source, replacing the previous "Public Preview" status.
> Resolves #460 - Remove Public Preview Header

- docs/config/overrides/main.html
- docs/how_to/parameterization.md
- src/fabric_cicd/_items/_environment.py
- src/fabric_cicd/_parameter/_parameter.py
- src/fabric_cicd/_parameter/_utils.py
- src/fabric_cicd/constants.py
- src/fabric_cicd/fabric_workspace.py
- tests/test_parameter.py
- tests/test_parameter_utils.py
This pull request introduces support for the `_ALL_` environment key in parameterization logic, allowing a single replacement value to be applied across all environments. The changes include documentation updates, logic for processing the `_ALL_` key, validation enhancements, and new tests. This provides a more flexible and user-friendly approach to environment-specific replacements.
**Parameterization enhancements:**
* Added support for the `_ALL_` (case-insensitive) environment key in `replace_value` for all parameter types. If present, it must be the only key and applies the replacement to any environment. Documentation was updated to explain this feature and provide usage examples. [[1]](diffhunk://#diff-9cdd02ee5f5219c5426160beb19ff83c624221fd6db2ac6f8bf923d6ebb6f0ffR225-R239) …
> Resolves #320 Support an "ALL" environment in parameter.yml

- .github/workflows/bump.yml
This pull request makes a minor change to the workflow dependencies in `.github/workflows/bump.yml`, removing the requirement for the `get-pr-details` job before running the `bump-version` job.
* Workflow update: The `bump-version` job now only depends on `validate-version-bump`, simplifying the workflow and potentially reducing execution time.
> Resolves #302 - Fix Bump Dependency

- docs/how_to/parameterization.md
- sample/workspace/Run Hello World.DataPipeline/.schedules
- sample/workspace/parameter.yml
- src/fabric_cicd/_common/_check_utils.py
- src/fabric_cicd/_parameter/_parameter.py
- src/fabric_cicd/fabric_workspace.py
- tests/test__check_utils.py
- tests/test_parameter.py
This pull request introduces enhancements and bug fixes to support key-value replacement in non-standard JSON files (such as `.schedules`), improve type safety and validation for parameter replacements, and expand test coverage for these scenarios. The main changes ensure that files with JSON content but non-`.json` extensions are correctly validated and processed, and that `key_value_replace` operations enforce type consistency across environments.
**Key improvements and fixes:**
* Added a sample `.schedules` file with valid JSON content to demonstrate and test key-value replacement in non-`.json` files.
* Updated `parameter.yml` to include a `key_value_replace` rule targeting the `enabled` field in `.schedules` files for different environments.
* Added `check_valid_json` (for files) and …
> Resolves #508 - Schedules Parameter Support

- src/fabric_cicd/fabric_workspace.py
- tests/test_fabric_workspace.py
This pull request removes support for the `base_api_url` keyword argument in the `FabricWorkspace` class and enforces the use of `constants.DEFAULT_API_ROOT_URL` for API root configuration. It also introduces a test to ensure that passing `base_api_url` raises an appropriate error.
Deprecation and error handling:
* Removed support for the `base_api_url` keyword argument in `FabricWorkspace.__init__`, now raising an `InputError` if it is provided, and updated the error message to guide users to use `constants.DEFAULT_API_ROOT_URL` instead.
API URL construction:
* Added a `base_api_url` property to `FabricWorkspace` that constructs the base API URL using `constants.DEFAULT_API_ROOT_URL` and the workspace ID.
Testing:
* Added a new test `test_base_api_url_kwarg_raises_error` to verify that …
> Resolves #529 - Deprecate Base API URL

- docs/how_to/item_types.md
- sample/workspace/sample apache airflow job.ApacheAirflowJob/.platform
- sample/workspace/sample apache airflow job.ApacheAirflowJob/apacheairflowjob-content.json
- sample/workspace/sample apache airflow job.ApacheAirflowJob/dags/dag1.py
- src/fabric_cicd/_items/__init__.py
- src/fabric_cicd/_items/_apacheairflowjob.py
- src/fabric_cicd/changelog.md
- src/fabric_cicd/constants.py
- src/fabric_cicd/publish.py
This pull request introduces support for Apache Airflow Jobs in the codebase, enabling these jobs to be managed and published as part of the CI/CD workflow. The changes include documentation updates, new sample files for an Airflow job, and corresponding updates to the code to recognize and publish this new item type.
**Apache Airflow Job support:**
* Added a new function `publish_apacheairflowjobs` in `src/fabric_cicd/_items/_apacheairflowjob.py` to handle publishing of Apache Airflow Job items.
* Registered the new publish function in the `src/fabric_cicd/_items/__init__.py` module and included it in the public API. [[1]](diffhunk://#diff-94d858110d4e75a68135b9975f58e289c7db48793b5bf7bc56c08efad59f3e34R5) [[2]](diffhunk://#diff-94d858110d4e75a68135b9975f58e289c7db48793b5bf7bc56c08efad59f …
> Resolves #565 Support Apache Airflow Job Item Type
