microsoft/fabric-cicd

.github/workflows/codeql.yml
This reverts commit ecc63706e51e2c9e743e21fadeedffc992c34d61.
=> Revert "Remove CodeQL"

devtools/debug_local.py, docs/changelog.md, docs/index.md, sample/workspace/ABC.Report/.platform, sample/workspace/ABC.Report/StaticResources/SharedResources/BaseThemes/CY24SU10.json, sample/workspace/ABC.Report/definition.pbir, sample/workspace/ABC.Report/report.json, sample/workspace/ABC.SemanticModel/.platform, sample/workspace/ABC.SemanticModel/definition.pbism, sample/workspace/ABC.SemanticModel/definition/cultures/en-US.tmdl, sample/workspace/ABC.SemanticModel/definition/database.tmdl, sample/workspace/ABC.SemanticModel/definition/model.tmdl, sample/workspace/ABC.SemanticModel/definition/relationships.tmdl, sample/workspace/ABC.SemanticModel/definition/tables/Table.tmdl, sample/workspace/ABC.SemanticModel/definition/tables/Table_2.tmdl, sample/workspace/Hello World.Notebook/notebook-content.py, src/fabric_cicd/_common/_exceptions.py, src/fabric_cicd/_common/_fabric_endpoint.py, src/fabric_cicd/_common/_validate_input.py, src/fabric_cicd/_items/__init__.py, src/fabric_cicd/_items/_report.py, src/fabric_cicd/_items/_semanticmodel.py, src/fabric_cicd/fabric_workspace.py, src/fabric_cicd/publish.py
This pull request includes several changes to add support for new item types and enhance existing functionalities. The most important changes include updates to the documentation, configuration files for new item types, and improvements to the error handling and logging mechanisms.
* [`docs/changelog.md`](diffhunk://#diff-77f023b99d3d58008351d3e82fc06e6d06ba1bc2da9e41be6329b7fa4f419f05L9-L13): Added support for `Lakehouse`, `Semantic Model`, and `Report` item types. Updated the release notes to include these new item types and changed the onboarding documentation to GitHub Pages. [[1]](diffhunk://#diff-77f023b99d3d58008351d3e82fc06e6d06ba1bc2da9e41be6329b7fa4f419f05L9-L13) [[2]](diffhunk://#diff-77f023b99d3d58008351d3e82fc06e6d06ba1bc2da9e41be6329b7fa4f419f05L22-R23)
* …
=> Onboard SemanticModel & Report ItemType

src/fabric_cicd/_common/_fabric_endpoint.py
This pull request includes changes to the `src/fabric_cicd/_common/_fabric_endpoint.py` file to improve the handling of JSON responses and simplify the code. The most important changes include replacing the `_parse_json_body` function with inline checks and ensuring consistent handling of JSON and non-JSON responses.
Improvements to JSON response handling:
* [`src/fabric_cicd/_common/_fabric_endpoint.py`](diffhunk://#diff-df48b77e163b4a13c97f80408ad6640fca48ffdc60c19e085b4c73589933178cL155-R159): Modified the error message construction to check for JSON content directly in the response headers.
* [`src/fabric_cicd/_common/_fabric_endpoint.py`](diffhunk://#diff-df48b77e163b4a13c97f80408ad6640fca48ffdc60c19e085b4c73589933178cL169-R173): Updated the response body parsing to handle JSON …
=> Reverts FabricEndpoint Changes Fixes #39

activate.ps1
This pull request includes significant improvements to the `activate.ps1` script, focusing on enhancing the dependency checking process and streamlining the activation of the virtual environment. The most important changes include adding a new function to check dependencies, refactoring existing code to use this new function, and improving the overall script structure.
Enhancements to dependency checking:
* [`activate.ps1`](diffhunk://#diff-ae3d5b16dbd3f471d5dc8e410e67f914643e73c93bfa1fd84792be63dbde63d6R21-R38): Added a new function `Test-Dependancy` to check if a dependency is available, provide feedback, and add the dependency's directory to the PATH if necessary.
Refactoring and code simplification:
* [`activate.ps1`](diffhunk://#diff-ae3d5b16dbd3f471d5dc8e410e67f914643e73c93bfa1fd8479 …
=> Fixes #87 - Support Python Installed from Windows Store

.github/workflows/unit-test.yml, README.md
This pull request includes the addition of a GitHub Actions workflow for running unit tests and an update to the `README.md` file to include a badge for the new workflow.
* [`.github/workflows/unit-test.yml`](diffhunk://#diff-d4223b44df678cece85f2542c19b9cd060d43b22f753c25214d5942ef2ca5d18R1-R23): Added a new workflow named "Tests" that runs on pull requests. The workflow sets up Python, installs dependencies, and runs unit tests using `pytest`.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R6): Added a badge to display the status of the new unit test workflow.
=> Onboard Unit Test Action

.github/workflows/unit-test.yml
This pull request includes a change to the GitHub Actions workflow configuration to trigger unit tests on both push and pull request events for the `main` branch.
* [`.github/workflows/unit-test.yml`](diffhunk://#diff-d4223b44df678cece85f2542c19b9cd060d43b22f753c25214d5942ef2ca5d18L3-R7): Updated the workflow to trigger on push events to the `main` branch in addition to pull requests to the `main` branch.
=> Update Test Trigger

mkdocs.yml, pyproject.toml, ruff.toml, src/fabric_cicd/__init__.py, src/fabric_cicd/_common/_check_utils.py, src/fabric_cicd/_common/_exceptions.py, src/fabric_cicd/_common/_fabric_endpoint.py, src/fabric_cicd/_common/_file.py, src/fabric_cicd/_common/_item.py, src/fabric_cicd/_common/_logging.py, src/fabric_cicd/_common/_validate_input.py, src/fabric_cicd/_items/_datapipeline.py, src/fabric_cicd/_items/_environment.py, src/fabric_cicd/_items/_notebook.py, src/fabric_cicd/_items/_report.py, src/fabric_cicd/_items/_semanticmodel.py, src/fabric_cicd/fabric_workspace.py, src/fabric_cicd/publish.py, uv.lock
This pull request focuses on updating the documentation style, adding new dependencies, and improving type annotations and docstrings across multiple files. The changes aim to standardize the codebase and enhance code readability and maintainability.
* [`mkdocs.yml`](diffhunk://#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2L62-R62): Changed the `docstring_style` from numpy to google.
* [`src/fabric_cicd/__init__.py`](diffhunk://#diff-364c25e03dde1816a460702e5c0224b29c1bd8d185d9eea1089520dd040c9849L23-R24): Updated docstring format to Google style in functions `append_feature_flag` and `change_log_level`. [[1]](diffhunk://#diff-364c25e03dde1816a460702e5c0224b29c1bd8d185d9eea1089520dd040c9849L23-R24) [[2]](diffhunk://#diff-364c25e03dde1816a460702e5c0224b29c1bd8d185d9e …
=> Standardize Docstrings

docs/changelog.md
This pull request includes changes to the `docs/changelog.md` file to enhance readability and organization by adding emojis to categorize different types of updates. The most important changes include the addition of new functionality, documentation updates, internal optimizations, and bug fixes.
Changes to `docs/changelog.md`:
* Added emojis to categorize updates into new functionality, bug fixes, documentation updates, and internal optimizations.
* Updated existing entries to use the new categories for better clarity.
=> Stylize Changelog

src/fabric_cicd/_common/_file.py, tests/test__file.py
This pull request includes changes to improve file handling and add a new test case for special characters. The most important changes include specifying the encoding when reading text files and adding a test to validate the handling of special characters.
Improvements to file handling:
* [`src/fabric_cicd/_common/_file.py`](diffhunk://#diff-46a7a9b8c61c3314a8ff6626e10767eaad7adaa4249e4cd24b90b181e574cdf0L61-R61): Modified the `__post_init__` method to specify `encoding="utf-8"` when reading text files to ensure proper handling of file contents.
Enhancements to testing:
* [`tests/test__file.py`](diffhunk://#diff-7790876c8eda26942e48f6e8f1761bd08797c4afdcbee0a5ff691df8b9c5bc7aR69-R92): Added a new test `test_special_characters_correct` to validate that files containing special characters …
=> Fixes #129 - Support for special characters

docs/how_to/parameterization.md
This pull request includes significant updates to the `parameter.yml` file structure and its associated documentation. The changes introduce new fields, enhance functionality, and provide more detailed guidance on parameterization and validation.
Key updates to `parameter.yml` documentation:
* **Important Notice**: Added a grace period from March 24, 2025, to April 24, 2025, for migrating to the new `parameter.yml` structure.
* **`find_replace` Updates**: Introduced `find_value` and `replace_value` fields, along with optional filters like `item_type`, `item_name`, and `file_path` for more precise replacements.
* **`spark_pool` Updates**: Updated structure to include `instance_pool_id`, `replace_value`, and optional `item_name` for filtering specific environment items.
* **Optional …
=> Resolved #113 Parameterization Refactor documentation updates

devtools/debug_parameterization.py, docs/config/pre-build/update_item_types.py, src/fabric_cicd/__init__.py, src/fabric_cicd/_common/_fabric_endpoint.py, src/fabric_cicd/_common/_validate_input.py, src/fabric_cicd/_items/_datapipeline.py, src/fabric_cicd/_parameter/_parameter.py, src/fabric_cicd/fabric_workspace.py, src/fabric_cicd/publish.py
This pull request focuses on consolidating the import of constants by using a single alias `constants` across multiple files in the `fabric_cicd` module. This change improves code readability and maintainability by standardizing the way constants are accessed.
Key changes include:
*Import standardization:*
* [`docs/config/pre-build/update_item_types.py`](diffhunk://#diff-dfc7e72547f63f32daeff960bb1258340b2453b0627b20204ddb67e7267cdfefL7-R15): Changed import of `ACCEPTED_ITEM_TYPES_UPN` to use `constants` alias.
* [`src/fabric_cicd/__init__.py`](diffhunk://#diff-364c25e03dde1816a460702e5c0224b29c1bd8d185d9eea1089520dd040c9849L9-R9): Updated import statements to use `constants` alias and modified references to constants accordingly. …
=> Fixes #190 Constants Imports

docs/how_to/parameterization.md, src/fabric_cicd/_parameter/_parameter.py, src/fabric_cicd/_parameter/_utils.py, src/fabric_cicd/constants.py
This pull request includes several changes to the parameter validation and replacement logic in the `fabric_cicd` module. The most important changes include updating the optional field handling, modifying the parameter validation function, and refining the messages and logging for better clarity.
* [`docs/how_to/parameterization.md`](diffhunk://#diff-9cdd02ee5f5219c5426160beb19ff83c624221fd6db2ac6f8bf923d6ebb6f0ffL71-R72): Updated the documentation to clarify that optional field values must match the corresponding properties in the repository file for replacements to occur.
* [`src/fabric_cicd/_parameter/_utils.py`](diffhunk://#diff-08e7f8767bb7d280f82e88a77521554115ad781c1dceb4ff0a7b450d38a684abL163-R163): Enhanced the `check_replacement` function to provide clearer logging messages and …
=> Resolves #192 Optional parameter validation causing unnecessary break in deployment

src/fabric_cicd/fabric_workspace.py
This pull request refactors the `_refresh_repository_folders` method in `fabric_workspace.py` to simplify its logic and improve performance by leveraging `Path.rglob`. Additionally, it updates the method signature to return `None` instead of a dictionary, aligning with its new behavior.
* Simplified folder traversal logic by using `Path.rglob` to collect folders containing `.platform` files and their subfolders, replacing the previous nested loops and multiple checks. This reduces complexity and improves maintainability.
* Updated the method signature to return `None` instead of a dictionary, as the method now directly assigns the processed folder hierarchy to `self.repository_folders`.
=> Fixes #255 Empty Folder Publishes

docs/how_to/item_types.md, sample/workspace/Hello Copy Job.CopyJob/.platform, sample/workspace/Hello Copy Job.CopyJob/copyjob-content.json, src/fabric_cicd/_items/__init__.py, src/fabric_cicd/_items/_copyjob.py, src/fabric_cicd/constants.py, src/fabric_cicd/publish.py
This pull request introduces support for a new item type, `CopyJob`, by adding documentation, configuration files, and implementation code. It also updates the existing codebase to integrate this new item type. Below is a breakdown of the most important changes:
* Added a new section in `docs/how_to/item_types.md` to document `CopyJob` parameterization and initial deployment requirements. This includes details about how connections are managed and parameterized during deployment. [[1]](diffhunk://#diff-2b5373cf38b50a290bee3f403778f7dff7cdc942ddbb39026b291da113dc6025R9) [[2]](diffhunk://#diff-2b5373cf38b50a290bee3f403778f7dff7cdc942ddbb39026b291da113dc6025R62-R67)
* Added `sample/workspace/Hello Copy Job.CopyJob/.platform` to define metadata and configuration for a `CopyJob` item.
* Added …
=> Resolves #122 Onboard CopyJob

docs/how_to/parameterization.md, pyproject.toml, sample/workspace/parameter.yml, src/fabric_cicd/_parameter/_parameter.py, src/fabric_cicd/_parameter/_utils.py, src/fabric_cicd/fabric_workspace.py, uv.lock
This pull request introduces a new feature for key-based replacement operations in JSON and YAML files, along with several enhancements to the parameterization functionality and updates to documentation. Key changes include the addition of the `key_value_replace` functionality, updates to the `find_replace` feature, and modifications to the codebase to support these new capabilities.
* Added a new `key_value_replace` functionality for performing key-based replacements in JSON and YAML files using JSONPath expressions. This feature allows for fine-grained control by filtering on `item_type`, `item_name`, and `file_path` attributes. [[1]](diffhunk://#diff-9cdd02ee5f5219c5426160beb19ff83c624221fd6db2ac6f8bf923d6ebb6f0ffR62-R80) [[2]](diffhunk://#diff-663a11b92ff45fa9b30ab4086a71af3d0f87fce5a8 …
=> Add key_value_replace

src/fabric_cicd/_parameter/_utils.py, src/fabric_cicd/fabric_workspace.py
Remove CodeQL comments as they are ineffective.
=> Remove CodeQL References

src/fabric_cicd/_items/_environment.py
Bugfix for issue  #336 , adding URL encoding to _remove_library file_name, fixes #336
=> Bug fix for issue #336, adding url encoding to _remove_library

src/fabric_cicd/_items/_manage_dependencies.py, src/fabric_cicd/constants.py
Changes to Fabric API URL to the public URL so users don't hit an ssl error.
=> Resolves #352 dataflow ssl error (fix fabric api url)

docs/how_to/parameterization.md
Updates the YAML Key in the example for Data Pipeline Parameterization.
Fixes space in the item type value
Resolves #396
=> Update Incorrect YAML Key Resolves #396

.github/workflows/validate.yml
Briefly describe what this PR does and why.
=> Resolves #302 - Automate Version Bump

.github/workflows/bump.yml
This pull request updates the logic in the `.github/workflows/bump.yml` workflow to more accurately detect version changes and the set of changed files, handling both workflow dispatch and pull request events. The changes improve reliability and correctness when determining which files have changed and what the previous and current version values are.
**Improvements to commit and file change detection:**
* The workflow now determines the correct commit to analyze based on the event type, using `needs.get-pr-details.outputs.pr_head_sha` for workflow dispatch events and `HEAD` for pull request events. This ensures the correct context is used for post-merge and manual runs.
* The method for listing changed files has been updated to compare the current commit with its parent (`git diff …
=> Resolves #302 - Fix Bump Workflow

src/fabric_cicd/_items/_report.py
This pull request makes a minor formatting change to the `$schema` assignment in the `func_process_file` function within `src/fabric_cicd/_items/_report.py`. No functional or behavioral changes are introduced.
=> Fixes #518 - Remove Trailing Comma
